### ISSUE TITLE
Cannot use 'Object' as class name as it is reserved

### ISSUE THREAD

**Issue by wumahoo** [raoul2000/yii2-workflow#58]
Hi，Cannot use 'Object' as class name as it is reserved，7.1 its end of life and is no longer supported.

**Comment by raoul2000** [comment]
Hi @wumahoo,
latest version (1.2.0) should be compliant with PHP 7.1 (see [CHANGES](https://github.com/raoul2000/yii2-workflow/blob/master/CHANGE.md#version-120)).

Did you experience an issue with this version ?
:sunglasses:

**Comment by wumahoo** [comment]
Hi @raoul2000 
 I upgraded my environment to PHP 7.2, but when I run it, I found that PHP 7.2 would not be able to use Object as its class name 

Will this be updated to work on PHP7.2?

**Comment by raoul2000** [comment]
if you use yii 2.0.13 + yii2-workflow 1.2.0 + PHP 7.2 then it is supposed to work.  The [travis-ci](https://travis-ci.org/raoul2000/yii2-workflow) test are also done on PHP 7.2 and they succeed.

You wrote that you updated your environment to PHP 7.2 but did you also update the Yii2 version ? ... if no, it is important to do so because only since version 2.0.13 yii2 is compatible with PHP 7.1 regarding the use of the reserved word *object*( see [YII2 CHANGES](https://github.com/yiisoft/yii2/blob/2.0.27/framework/CHANGELOG.md#2013-november-03-2017) - change #7936)

hope this helps
😎

**Comment by wumahoo** [comment]
cornernote/yii2-workflow-manager  not supposed
